// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type PostLog struct {
	ID        string
	SessionID string
	TagName   string
	CreatedAt time.Time
	PairID    string
}
