// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: post_log.sql

package sqlc

import (
	"context"
)

const addPostLog = `-- name: AddPostLog :exec
INSERT post_log (id, session_id, pair_id, tag_name) VALUES (?, ?, ?, ?)
`

type AddPostLogParams struct {
	ID        string
	SessionID string
	PairID    string
	TagName   string
}

func (q *Queries) AddPostLog(ctx context.Context, arg AddPostLogParams) error {
	_, err := q.db.ExecContext(ctx, addPostLog,
		arg.ID,
		arg.SessionID,
		arg.PairID,
		arg.TagName,
	)
	return err
}
